name: Test
on:
  push:  
    branches: [ master ]
  
  workflow_dispatch: 

jobs:  
  my_testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run:
          pip install -r requirements.txt     
      - name: run pytest
        run:
          pytest -v
      
      - name: build
        run:     
          docker build -f Dockerfile -t kotovak/app:$GITHUB_SHA .
          echo $GITHUB_SHA
         
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: kotovak/app:latest
