name: CI

on:
  push:  
    branches: [ master ]
  
  workflow_dispatch: 

jobs:  
  my_testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Print hello masseges
        run: echo "Hello, world from testing!"
  
  my_depoy:
     runs-on: ubuntu-latest
     
     steps:
      - name: Print hello masseges
        run: echo "Hello, world from deploy!"
        
